name: attractivia
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  auto_animated: ^3.2.0
  flutter_displaymode: ^0.7.0
  get: ^4.7.2
  get_storage: ^2.1.1
  provider: ^6.1.5+1
  flutter_screenutil: ^5.9.3
  rxdart: ^0.28.0
  dio: ^5.9.0
  intl: ^0.20.2
  device_info_plus: ^12.1.0
  get_it: ^8.2.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.2.3
  camera: ^0.11.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  video_player: ^2.10.0
  path: ^1.9.1
  carousel_slider: ^5.1.1
  lottie: ^3.3.2
  record: ^6.1.2
  just_audio: ^0.10.5
  audio_waveforms: ^1.3.0
  audioplayers: ^6.5.1
  image_picker: ^1.2.0
  google_mlkit_document_scanner: ^0.4.0
  pdf: ^3.11.3
  open_filex: ^4.7.0
  flutter_doc_scanner: ^0.0.16
  photo_view: ^0.15.0
  flick_video_player: ^0.9.0
  flutter_widget_from_html: ^0.17.1
  url_launcher: ^6.3.2
  pinput: ^6.0.1
  pin_code_fields: ^8.0.1
  syncfusion_flutter_gauges: ^32.1.19
  flutter_fortune_wheel: ^1.3.2
  flutter_otp_text_field: ^1.5.1+1
  signature: ^6.3.0
  

dev_dependencies:
  dependency_validator: ^5.0.3
  flutter_gen_runner: 
  build_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80


  colors:
    inputs:
      - assets/colors/color.xml
    outputs:
      class_name: AppColors

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/colors/
   
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: figtree
  #     fonts:
  #       - asset: assets/fonts/Figtree[wght].ttf
  #       - asset: assets/fonts/Figtree-Italic[wght].ttf
  #   - family: Manrope
  #     fonts:
  #       - asset: assets/fonts/Manrope-Bold.ttf
  #       - asset: assets/fonts/Manrope-ExtraBold.ttf
  #       - asset: assets/fonts/Manrope-ExtraLight.ttf
  #       - asset: assets/fonts/Manrope-Light.ttf
  #       - asset: assets/fonts/Manrope-Medium.ttf
  #       - asset: assets/fonts/Manrope-Regular.ttf
  #       - asset: assets/fonts/Manrope-SemiBold.ttf
    
    # - family: glacialIndifference
    #   fonts:
    #     - asset: assets/fonts/glacialIndifference.ttf

    # - family: GlacialIndifferencBold
    #   fonts:
    #     - asset: assets/fonts/GlacialIndifferencBold.otf

        
    # - family: awesomeSerifERegular
    #   fonts:
    #     - asset: assets/fonts/awesomeSerifERegular.ttf
        
    # - family: assomweItalicRegular
    #   fonts:
    #     - asset: assets/fonts/assomweItalicRegular.ttf

    # - family: AwesomeSerif
    #   fonts:
    #     - asset: assets/fonts/AwesomeSerif.otf

    # - family: AwesomeSerifExtraTall
    #   fonts:
    #     - asset: assets/fonts/AwesomeSerifExtraTall.otf

    # - family: AwesomeSerifLightExtraTall
    #   fonts:
    #     - asset: assets/fonts/AwesomeSerifLightExtraTall.otf
  
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
